FROM ruby:2.6-rc-alpine

# Configuration.
ENV LANG C.UTF-8
WORKDIR /app

# Installation.
COPY flashcards.gemspec Gemfile Gemfile.lock ./
RUN apk --update add --virtual build-dependencies ruby-dev build-base ncurses-dev && bundle install
COPY . .

# The entry point.
# Note that here we are using CMD rather than ENTRYPOINT.
# This is for convenience in development.
CMD ["bundle", "exec", "bin/flashcards"]
