desc 'Run the app.'
task :run do
  sh 'chruby-exec jruby -- ./app.rb'
end

desc 'Package the app.'
task :pack do
  sh 'chruby-exec jruby -- shoes -p swt:app -p swt:jar app.yaml'
end

task default: :run
